[package]
name = "rerun_logger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dora-node-api = { version = "0.3.0" }
rerun = { version = "0.11.0" }
image = {version = "*"}