[package]
name = "plot_stereo_image"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dora-node-api = { version = "0.3.0" }
opencv = { version = "0.88.1" }
